#!/usr/bin/env python3
#
# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
import pathlib
import re
import sys

import kernel_processing


_UTS_RELEASE_RE = re.compile(
    r'\d+\.\d+\.\d+-android\d+-\d+(?P<scmversion>(?:-[^-]+)+?)(?:-\d+k)?'
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', type=pathlib.Path, required=True)
    parser.add_argument('--out', type=pathlib.Path, required=True)
    args = parser.parse_args()

    if not args.image.is_file():
        print(f'Image file not found at {args.image}', file=sys.stderr)
        return 1

    try:
        linux_banner = kernel_processing.get_linux_banner(
            args.image.read_bytes()
        )
    except ValueError as err:
        print(f'Error in processing linux banner: {err}', file=sys.stderr)
        return 1

    release_match = _UTS_RELEASE_RE.fullmatch(linux_banner.uts_release)
    if release_match is None:
        print(
            f"UTS release '{linux_banner.uts_release}' has unrecognised format",
            file=sys.stderr,
        )
        return 1

    workspace_status = {
        'SCMVERSION': release_match['scmversion'],
        'SOURCE_DATE_EPOCH': linux_banner.epoch,
    }
    args.out.write_text(json.dumps(workspace_status))
    return 0


if __name__ == '__main__':
    sys.exit(main())
