#!/bin/bash

partition="$1"

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <partition>" 1>&2
  exit 1
fi

echo "# begin sku build properties"
echo "# autogenerated by $0"

echo "ro.${partition}.build.fingerprint=$BUILD_FINGERPRINT_SKU"

echo "ro.product.${partition}.brand=$PRODUCT_BRAND_SKU"
echo "ro.product.${partition}.device=$PRODUCT_DEVICE_SKU"
echo "ro.product.${partition}.manufacturer=$PRODUCT_MANUFACTURER_SKU"
echo "ro.product.${partition}.model=$PRODUCT_MODEL_SKU"
echo "ro.product.${partition}.name=$PRODUCT_NAME_SKU"
echo "ro.product.${partition}.marketname=$PRODUCT_MARKETNAME_SKU"
echo "ro.product.${partition}.cert=$PRODUCT_CERT_SKU"

echo "# end sku build properties"
