#!/bin/bash -e

# Copyright (C) 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ABIGAIL_VERSION=1.6

NUM_CORES=$(cat /proc/cpuinfo | grep -c proc)
BASE_DIR=$(readlink -f $(dirname $0))
OUT_DIR="${BASE_DIR}/abigail-inst/${ABIGAIL_VERSION}"
LIBABIGAIL_SRC="${BASE_DIR}/abigail-src"

# Check output dir.
if [ -e "${OUT_DIR}" ]; then
  echo "WARN: ${OUT_DIR} exists. Press enter to continue or Ctrl-C to abort."
  read
fi

set -x

PACKAGES="libxml2-dev elfutils libdw-dev"
# Install the dependencies.
if ! dpkg -s ${PACKAGES} > /dev/null 2>&1 ; then
    sudo apt-get install ${PACKAGES}
fi

if [ ! -d "${LIBABIGAIL_SRC}" ]; then
  git clone git://sourceware.org/git/libabigail.git "${LIBABIGAIL_SRC}"
else
  git -C ${LIBABIGAIL_SRC} fetch
fi

git -C ${LIBABIGAIL_SRC} checkout libabigail-${ABIGAIL_VERSION}

# Build libabigail
pushd "${LIBABIGAIL_SRC}"
  #git clean -dfx
  autoreconf -i --force
  mkdir -p build/
  pushd build/
    ../configure --prefix="${OUT_DIR}" --enable-cxx11=yes --disable-shared
#    make -j${NUM_CORES}
    make -j${NUM_CORES} install-exec
  popd
popd

set +x

echo
echo "Note: Export following environment before running the executables:"
echo
echo "export PATH=\"${OUT_DIR}/bin:\${PATH}\""
echo
echo
