#!/bin/bash

# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$#" -ne 2 ]; then
	echo "ERROR: illegal number of parameters" >&2
	echo "Usage: compare_to_wl <path/to/Module.symvers> <path/to/symbol-list>" >&2
	exit 1
fi

ksymtab=$(mktemp)
symbollist=$(mktemp)

# List of objects, typically vmlinux + GKI modules
objects="${KMI_STRICT_MODE_OBJECTS:-vmlinux}"
objects=($objects)

# Parse Module.symvers, and ignore non-exported and vendor-specific symbols
cut -d$'\t' -f2- $1 | while read line; do
	ksym=($line) # 0=symbol name; 1=object name; 2=export type
	if [[ "${ksym[2]}" != "EXPORT_SYMBOL"* ]]; then
		continue
	elif [[ ! " ${objects[@]} " =~ " ${ksym[1]} " ]]; then
		continue
	fi
	echo "${ksym[0]}"
done | sort -u > $ksymtab

sort -u "$2" > $symbollist

delta=$(diff -u $ksymtab $symbollist | grep -v ' ')
rm $ksymtab $symbollist
if [ -n "$delta" ]; then
	echo "ERROR: Differences between ksymtab and symbol list detected!" >&2
	echo "Symbols missing from ksymtab:" >&2
	echo "$delta" | sed -n -e 's/^+/ - /p' >&2
	echo "Symbols missing from symbol list:" >&2
	echo "$delta" | sed -n -e 's/^-/ - /p' >&2
	exit 1
fi
